definitions:
  main.User:
    properties:
      email:
        type: string
      id:
        type: integer
      password:
        description: In practice, hash the password before storing it
        type: string
      phone:
        type: string
    type: object
info:
  contact: {}
paths:
  /register:
    post:
      consumes:
      - application/json
      description: Register a new user with email and phone
      parameters:
      - description: User object for registration
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/main.User'
      produces:
      - application/json
      responses:
        "201":
          description: User registered successfully
          schema:
            type: string
        "400":
          description: Invalid input data
          schema:
            type: string
        "409":
          description: Email or phone number already registered
          schema:
            type: string
      summary: Register a new user
      tags:
      - users
swagger: "2.0"
